enum key_numbers{
	KESC,K1,K2,K3,K4,K5,K6,K7,K8,K9,K0,KMin,KEQ,KBACK,KINS,
	KTAB,KQ,KW,KE,KR,KT,KY,KU,KI,KO,KP,KBROP,KBRCL,KBSL,KDEL,
	KCLOCK,KA,KS,KD,KF,KG,KH,KJ,KK,KL,KCOLON,KQUOTE,KENTER,KHOME,
	KLSHIFT,KZ,KX,KC,KV,KB,KN,KM,KSEMI,KDOT,KSLASH,KRSHIFT,KUP,
	KLCTL,KWIN,KLALT,KSPACE,KRALT,KFN1,KFN2,KLEFT,KDOWN,KRIGHT
	};
